# Torrent from qBittorrent through the Tor network (not recommended)
# If you can, use qbittorrent+gluetun instead.
# Beware: It will be often dead slow

# Purely for educational purposes and not intended for illegal use.

# ! Why should we not use Tor for torrenting?
# * Torrenting via Tor strains limited bandwidth, degrading performance for others. 
# *   Torrent clients can leak your real IP, compromising anonymity. 
# *   Tor exit nodes face legal risks from torrent traffic. 
# *   Tor isn't optimized for high-bandwidth tasks like torrenting. 
# *   Some exit nodes block BitTorrent due to these issues.
# *   Not to mention, they don't support UDP, which is required for DHT and PEX. 

version: '3'
services:
  tor:
    container_name: tor-socks5
    image: dperson/torproxy
    restart: always
    networks:
      - tor_network
      
  # Follow the below link to connect qB to a socks5 proxy
  # https://vpn.ac/knowledgebase/93/qBittorrent-SOCKS5-setup-instructions.html
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /AppData/qbittorrent/config:/config
      - /home/user/Downloads/Torrents:/downloads
    ports:
      - 8080:8080
    networks:
      - tor_network
    restart: unless-stopped

networks:
  tor_network:
    driver: bridge
